service: my-express-app

provider:
  name: aws
  runtime: nodejs20.x  # Specify Node.js runtime version
  region: ap-south-1  # Specify AWS region

functions:
  app:
    handler: index.handler  # Correct the handler to point to index.js
    events:
      - http:
          path: /  # Handles the root URL
          method: any  # Handles all HTTP methods (GET, POST, etc.)
      - http:
          path: /{proxy+}  # Catches all other paths
          method: any  # Handles all HTTP methods

plugins:
  - serverless-offline  # For testing locally

environment:
  API_PREFIX: "/api/v1"  # Set the API_PREFIX environment variable
  PORT: 4000  # Default port, although AWS Lambda doesn't use it
