service: my-express-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    # Global environment variables loaded from .env file
    API_PREFIX: '/api/v1'
    DB_COLLECTION: ${env:DB_COLLECTION}
    DB_NAME: ${env:DB_NAME}
    MAIL_ENCRYPTION: ${env:MAIL_ENCRYPTION}
    MAIL_FROM_NAME: ${env:MAIL_FROM_NAME}
    MAIL_HOST: ${env:MAIL_HOST}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    MAIL_PORT: ${env:MAIL_PORT}
    MAIL_SERVICE: ${env:MAIL_SERVICE}
    MAIL_USERNAME: ${env:MAIL_USERNAME}
    PORT: ${env:PORT}
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /  # Define root path
          method: any
      - http:
          path: /{proxy+}  # Catch-all proxy path
          method: any

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
